version: '3.7'

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=elk-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/es01/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elk

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=elk-docker-cluster
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/es02/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=elk-docker-cluster
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/es03/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.2
    container_name: logstash
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/data:/usr/share/logstash/data        #  data folder will be here  ( gour.json ) 
    ports:
      - 5044:5044
    depends_on:
      - es01
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logstash/data:/data:ro   #  (it will read data of gour.json here)  
    depends_on:
      - logstash
    networks:
      - elk

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.13.2
    container_name: metricbeat
    user: root
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    depends_on:
      - es01
    networks:
      - elk

networks:
  elk:
    driver: bridge

